README.md
src/elements/containers/border.rs
src/elements/containers/floating.rs
src/elements/containers/scroll.rs
src/elements/custom.rs
src/elements/image.rs
src/elements/mod.rs
src/elements/rectangle.rs
src/elements/text.rs
src/id.rs
src/layout/mod.rs
src/lib.rs
src/math.rs

This PR has a lot of stuff:
- Adding `Custom` element
- Adding support of ids
- Moving some stuff around
- Adding some clay functions
- Converting all `Into`s into `From`s to avoid having both
- Text measuring stuff (set measuring function on clay object and shenanigans to make the `extern "C" fn` pointer work)

Global improvements to the codebase and minor bindings stuff

---

build.rs

Currently you get lots of warnings when you build `clay.h` This will disable them until they are fixed.

Remove extra warnings until they are fixed

---

src/elements/containers/border.rs
src/elements/containers/floating.rs
src/elements/containers/scroll.rs
src/elements/custom.rs
src/elements/image.rs
src/elements/mod.rs
src/elements/rectangle.rs
src/elements/text.rs
src/layout/alignment.rs
src/layout/mod.rs
src/layout/padding.rs
src/layout/sizing.rs
src/lib.rs
src/render_commands.rs

The current API doesn't make it easy to support RenderCommands in it's current state, making it mandatory to duplicate code/structs
So this new API should allow use on the two fronts. Some things were changed a bit, other were completly replaced.
PS. `Text` is still not working because we are waiting on what clay does with this

New API front and back to support RenderCommands

---

src/render_commands.rs

Now we pass in a `&str` reference instead. Notice that doing  `.to_string()` will cause a memory allocation which isn't needed here. In order to fix this correctly I had to introduce lifetimes to tell the compiler how the string lives on, but nothing that was a big hurdle to implement.

no-std fixes and removed String usage

---

.cargo/config.toml
.github/workflows/ci.yaml

When we start adding more tests we will run into the issue that `Clay` is single threaded. This make sure that our tests will run correctly.

Preparation for more tests

---

.github/workflows/ci.yaml
build.cpp
build.rs

In order to build Windows I had to add an extra build.cpp just for Windows (setting `compile as cpp` in `cc` didn't work) and this file is small is just used for compiling `clay.h` so I think it makes sense to just have it twice.
The only way I was able to get `Clay` compiling was as cpp with `std++20` enabled so that is what I will use for it.

Fixed so Windows compiles again

---

src/color.rs

Added the `const` modifier to the `Color` constructor functions.

`Color::rgb` ,`rgba`, `u_rgb` and `u_rgba` are now `const`

---

src/layout/sizing.rs

Added shorthand macros for the `Sizing` values and tests to make sure they're equivalent to creating the equivalent values manually.

Adding macros for the `Sizing` values

---

.github/workflows/ci.yaml
examples/basic_rectangle.rs
src/layout/sizing.rs

Before the Clippy would run, but wouldn't generate any error if it found issues. I changed now so the build will fail to make sure we catch these issues and same with `cargo fmt` I also changed so we only run `cargo fmt` and `cargo clippy` once (on Linux only)

fmt & clippy fixes + better CI

---

.cargo/config.toml
clay.h
src/bindings/bindings.rs
src/bindings/bindings_debug.rs
src/lib.rs

Clay has now added multi-context support so I changed so that we set the active context when we do a `with(...)` I would have preferred that a context was always passed into the functions instead, but this is the way it was implemented.
With this I also removed the config that would force testing threads to one.

Updated Clay with multi-context support

---

examples/basic_rectangle.rs
src/elements/containers/border.rs
src/elements/containers/floating.rs
src/elements/containers/scroll.rs
src/elements/custom.rs
src/elements/image.rs
src/elements/rectangle.rs
src/id.rs
src/lib.rs

This changes how IDs are handled. They now matches closer to the Odin bindings in that they don't depend on other primitives being added during the setup.
Also changed so only `static str` are accepted to to `Id::new(...)` to enforce proper lifetimes.

Id now returns TypedConfig

---

clay.h
src/bindings/bindings.rs
src/bindings/bindings_debug.rs
src/layout/padding.rs
src/lib.rs

* Updated to latest Clay
* New Clay changes the padding so it's now `left, right, top, bottom` So changed the `Padding` struct to allow for easier access of setting this data
* New Clay adds access to the `BoundingBox` based on ID so added access to that. The Rust version uses `Option` here instead of a struct + bool

Added new padding & boundingbox access

---

clay.h
src/bindings/bindings.rs
src/bindings/bindings_debug.rs
src/lib.rs

I added user_data pointer to the measure text callback yesterday and here is the added support for the Rust wrapper. I have added so there are two function
```Rust
set_measure_text_function_user_data(&mut m_data, | ... | ... );
set_measure_text_function(| ... | ... );`
```
Example
```Rust
let mut callback_data = 0u32;
let mut clay = Clay::new(Dimensions::new(800.0, 600.0));
clay.set_measure_text_function_user_data(&mut callback_data, |text, _config, data| {
println!(
"set_measure_text_function_user_data {:?} count {:?}",
text, data
);
**data += 1;
Dimensions::default()
});
```
Also the new set function makes sure that captures works correct (which requires boxing and such) also lifetimes should be correct now as well (if you move the `u32` above to be create after the `Clay` object you …

Support measure text with user data

---

src/elements/containers/border.rs

When I started to look into adding border rending I notice that it wasn't possible to access the border data so I have now fixed that.

Make sure Border data can be accessed

---

build.rs
clay.h
src/bindings/bindings.rs
src/bindings/bindings_debug.rs
src/lib.rs
src/render_commands.rs

* Updated to latest Clay that includes `z_offset` in the rendering
* In `build.rs` fixed so the C code gets rebuild if `clay.h` changes
* `Clay_StringSlice` is now used for the in the `RenderCommand` so added a convert to `&str` for that. I'm not sure if we want to expose the base address at some point, but I left it as is for now.

Latest Clay that includes z_offset for rendering

---

.github/workflows/ci.yaml
.vscode/settings.json
Cargo.toml
README.md
examples/raylib_renderer.rs
src/lib.rs
src/raylib.rs

this PR partially ports the raylib renderer from clay into rust. it also adds an example section in the README, and an example to demonstrate the raylib renderer.

feat: raylib renderer

---

examples/basic_rectangle.rs
examples/raylib_renderer.rs
src/bindings/bindings.rs
src/bindings/bindings_debug.rs
src/elements.rs
src/layout.rs
src/lib.rs
src/raylib.rs
src/render_commands.rs

This PR improves the typesafety of the render commands, more specifically, it ensures that what you put inside the declaration is what the renderer is expecting.
For that to be possible, 2 new generic types were added to the Clay struct, ImageElementData and CustomElementData, which then are forwarded to the ImageBuilder struct and Declaration::custom_data function and to the RenderCommand struct. With this change we can prevent undefined behavior when rendering images and custom elements at compile time.
This was not the only change, additionally, the custom_element function was also added back because it was missing from the Declaration struct

feat!: improve typesafety on image and custom elements

---

.cargo/config.toml
.gitignore
src/lib.rs

When passing in a closure with no capture Rust ZST would optimize this so no real pointer would be returned from the Box which would cause a crash later when dropping it
Also added a new test for this, but had to set thread tests count to 1 because Clay isn't thread-safe yet even if it has it's context stuff added to it.

Fixed crash on Drop

---

src/lib.rs

You can't use the Clay struct when you're inside a clay scope so you couldn't use these functions so this basically adds these 2 methods on ClayLayoutScope which are just proxies to the original methods from the clay struct

feat: forward scroll_container_data and bounding_box methods in clay scope

---

Cargo.toml
clay.h
examples/wgpu/ui_layout.rs
src/bindings/bindings.rs
src/bindings/bindings_debug.rs
src/lib.rs
src/render_commands.rs
src/text.rs

This updates to latest Clay with a bunch of changes:
* Clay always hash strings now so the flag we used to track this has now been removed
* Scroll has been renamed to Clip so I have updated the API to reflect this
* Added missing corner_radii to RenderImage
* Bump version to 0.3.0 because of breaking change with Scroll/Clip

Update to latest Clay
